ignore:
  - "client/coverage"
  - "client/node_modules"
  - "client/public"
  - "client/src/img"
  - "client/src/types"
  - "client/setupTest.ts"
  - "client/reportWebVitals.ts"
  - "client/react-app-env.d.ts"
  - "client/index.tsx"
