version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 27017:27017

  db_qube:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - TS_CONFIG_FILE=./tsconfig.json
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./server:/server-dir
      - ./server/tsconfig.json:/server-dir/tsconfig.json:ro

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client-dir
    depends_on:
      - server

  sonarqube:
    image: sonarqube:community
    depends_on:
      - db_qube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "0.0.0.0:9000:9000"
    networks:
      - sonarqube_network

networks:
  sonarqube_network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
