name: Workflow per Code Coverage
on:
  push:
    branches:
      - dev
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
