name: Workflow per Code Coverage
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        working-directory: ./client
        run: |
          npm ci && 
          npm run build && 
          npm run coverage -- --config=./.github/codecov.yml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
