name: Test Coverage

on: [push, pull_request]

jobs:
  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update npm
        run: npm install -g npm@latest

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Run test coverage
        working-directory: ./client
        run: npm run coverage
